[package]
name = "fluxqueue-worker"
version = "0.3.2"
edition = "2024"

[lib]
name = "fluxqueue_worker"
path = "src/lib.rs"

[[bin]]
name = "fluxqueue-worker"
path = "src/main.rs"

[dependencies]
pythonize = "0.28.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "fmt",
  "time",
] }
time = { version = "0.3.47", features = ["local-offset", "macros"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
chrono = "0.4.44"
num_cpus = "1.17.0"
futures = "0.3.32"

pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-async-runtimes.workspace = true
tokio = { workspace = true, features = ["macros", "signal", "time"] }
redis = { workspace = true, features = ["script"] }
deadpool-redis.workspace = true
serde.workspace = true
anyhow.workspace = true
uuid.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true

fluxqueue-common.workspace = true
