name: "Build Python Package"
description: "Build and package the library"
inputs:
  python-version:
    description: "Python version"
    required: true
  target:
    description: "Target to build the package for"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        args: --release --out dist --find-interpreter
        sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ inputs.target }}
        path: dist
