[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
repository = "https://github.com/CCXLV/fluxqueue"
homepage = "https://fluxqueue.ccxlv.dev"
authors = ["Giorgi Merebashvili <mereba2627@gmail.com>"]

[workspace.dependencies]
pyo3 = "0.28.3"
pyo3-async-runtimes = { version = "0.28.0", features = ["tokio-runtime"] }
tokio = { version = "1.52.1", features = ["rt-multi-thread"] }
anyhow = "1.0.102"
redis = "1.2.1"
deadpool-redis = { version = "0.23.0", features = ["rt_tokio_1"] }
serde = { version = "1.0.228", features = ["derive"] }
rmp-serde = "1.3.1"
rmpv = { version = "1.3.1", features = ["with-serde"] }
uuid = { version = "1.23.1", features = ["v4"] }

fluxqueue-common = { path = "./crates/fluxqueue-common" }
