[package]
name = "fluxqueue-common"
version = "0.1.0"
edition = "2024"

[lib]
name = "fluxqueue_common"
path = "src/lib.rs"

[dependencies]
serde-pyobject = "0.8.0"

pyo3.workspace = true
deadpool-redis.workspace = true
serde.workspace = true
anyhow.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true
uuid.workspace = true
